### ISSUE TITLE
how would you trigger the autocompletion when "#" is prepended

### ISSUE THREAD

**Issue by gbertb** [gwadhwani/MPGTextField#8]
Would like the autocompletion to start when a character like "#" is typed in

**Comment by mnearents** [comment]
You can probably achieve this by subclassing the MPGTextField, overriding the applyFilterWithSearchQuery method, and changing the predicate so that the query begins with "#" and then whatever follows to match your data source. 

Try this to build your predicate: http://stackoverflow.com/a/8371325/1391672

This is the method you would override:

```
- (NSArray *)applyFilterWithSearchQuery:(NSString *)filter
{


NSPredicate *predicate = [NSPredicate predicateWithFormat:@"INSERT YOUR NSPREDICATE HERE", filter];


NSArray *filteredGoods = [NSArray arrayWithArray:[data filteredArrayUsingPredicate:predicate]];
return filteredGoods;
```

}
